version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: race_db
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  web:
    volumes:
    - ./tmp:/tmp
    build: ./server
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:rootpassword@db:3306/race_db
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
