name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          if ! docker compose version; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-linux-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

      - name: Build and run containers
        run: |
          docker compose up -d --build

      - name: Wait for DB healthcheck
        run: |
          until [ "`docker inspect -f {{.State.Health.Status}} eventstride-db-1`" == "healthy" ]; do
            echo "Waiting for DB to become healthy..."
            sleep 5
          done

      - name: Wait for frontend healthcheck
        run: |
          until curl -s http://localhost:3000; do
            echo "Waiting for frontend to become accessible..."
            sleep 5
          done

      - name: Wait before tear down
        run: sleep 5

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down
